const { SlashCommandBuilder, AttachmentBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, MessageFlags } = require('discord.js');
const { getHero } = require('../systems/hero/heroService');
const { getActiveExpedition, getDailyLocations, computeSuccessChance, nextBossAt } = require('../systems/hero/expeditionService');
const { getActiveBuffs } = require('../systems/hero/alchemyService');
const { createGuildCard } = require('../images/hero/createGuildCard');
function rows(uid){return [new ActionRowBuilder().addComponents(
 new ButtonBuilder().setCustomId(`guild:home:${uid}`).setLabel('Гильдия').setEmoji('🏰').setStyle(ButtonStyle.Primary),
 new ButtonBuilder().setCustomId(`guild:expeditions:${uid}`).setLabel('Экспедиции').setEmoji('🧭').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`guild:alchemy:${uid}`).setLabel('Алхимия').setEmoji('🧪').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`guild:boss:${uid}`).setLabel('World Boss').setEmoji('👹').setStyle(ButtonStyle.Danger)
)];}
async function home(interaction,edit=false){const hero=getHero(interaction.user.id);if(!hero){const p={content:'❌ Сначала создай героя через `/hero create`.',flags:MessageFlags.Ephemeral};return edit?interaction.update(p):interaction.reply(p);}const active=getActiveExpedition(interaction.user.id),next=nextBossAt();const buffer=await createGuildCard(hero,interaction.user,active,next);const p={content:'## 🏰 Гильдия героев Game Syndicate',files:[new AttachmentBuilder(buffer,{name:'gs-hero-guild.png'})],components:rows(interaction.user.id)};return edit?interaction.update(p):interaction.editReply(p);}
module.exports={data:new SlashCommandBuilder().setName('guild').setDescription('Открыть интерактивное меню Гильдии героев'),async execute(interaction){await interaction.deferReply();return home(interaction,false);},async handleComponent(interaction){const [_,page,owner]=interaction.customId.split(':');if(owner!==interaction.user.id)return interaction.reply({content:'Это меню принадлежит другому участнику.',flags:MessageFlags.Ephemeral});if(page==='home')return home(interaction,true);const hero=getHero(interaction.user.id);if(!hero)return interaction.reply({content:'Сначала создай героя.',flags:MessageFlags.Ephemeral});if(page==='expeditions'){const active=getActiveExpedition(interaction.user.id);const locs=getDailyLocations(interaction.guildId||'dm');const text=locs.map(l=>`${l.dailyTheme.icon} **${l.name} — ${l.dailyTheme.name}**\n${l.description}\n🎯 ${Math.round(computeSuccessChance(hero,l))}% • ⏳ 4 ч.\n${l.dailyTheme.description}`).join('\n\n');return interaction.update({content:'## 🧭 Экспедиции гильдии',embeds:[new EmbedBuilder().setColor(0x7c3aed).setDescription(text).setFooter({text:active?'Твой герой уже в экспедиции.':'Выбор и запуск: /expedition start'})],files:[],components:rows(owner)});}if(page==='alchemy'){const buffs=getActiveBuffs(interaction.user.id);const text=buffs.length?buffs.map(b=>`✨ **${b.source_item_key}** • ${b.context==='world_boss'?'World Boss':'Экспедиция'} • зарядов ${b.charges}`).join('\n'):'Активных эффектов нет. Открой `/alchemist`, чтобы создать и применить расходники.';return interaction.update({content:'## 🧪 Алхимическая мастерская',embeds:[new EmbedBuilder().setColor(0xa855f7).setDescription(text)],files:[],components:rows(owner)});}if(page==='boss'){const next=nextBossAt();return interaction.update({content:'## 👹 Мировой босс',embeds:[new EmbedBuilder().setColor(0xdc2626).setDescription(`Бои проходят ежедневно в **15:00** и **21:00 МСК**.\n\nСледующий сбор: <t:${Math.floor(next.getTime()/1000)}:R>.\n\nГерой, находящийся в экспедиции, не сможет зарегистрироваться на бой.`)],files:[],components:rows(owner)});}}};
