const RECIPES = Object.freeze({
  rusty_blade: { itemKey:'rusty_blade', npc:'Кузнец Бран', dust:140, level:1, materials:{ iron_ingot:9, board:4 } },
  hunters_bow: { itemKey:'hunters_bow', npc:'Кузнец Бран', dust:160, level:1, materials:{ board:13, leather:4 } },
  novice_staff: { itemKey:'novice_staff', npc:'Кузнец Бран', dust:175, level:1, materials:{ board:11, crystal:2 } },
  patched_leather: { itemKey:'patched_leather', npc:'Кузнец Бран', dust:190, level:1, materials:{ leather:15, board:4 } },
  leather_cap: { itemKey:'leather_cap', npc:'Кузнец Бран', dust:130, level:1, materials:{ leather:9 } },
  worn_boots: { itemKey:'worn_boots', npc:'Кузнец Бран', dust:160, level:1, materials:{ leather:11, board:2 } },
  copper_ring: { itemKey:'copper_ring', npc:'Кузнец Бран', dust:210, level:2, materials:{ iron_ingot:7, crystal:2 } },
  forest_amulet: { itemKey:'forest_amulet', npc:'Кузнец Бран', dust:230, level:2, materials:{ board:9, herb:7, essence:2 } },
  iron_axe: { itemKey:'iron_axe', npc:'Кузнец Бран', dust:455, level:3, materials:{ iron_ingot:26, board:9, stone:4 } },
  chainmail: { itemKey:'chainmail', npc:'Кузнец Бран', dust:525, level:3, materials:{ iron_ingot:33, leather:9 } },
  iron_helm: { itemKey:'iron_helm', npc:'Кузнец Бран', dust:420, level:3, materials:{ iron_ingot:22, leather:4 } },
  duelist_gloves: { itemKey:'duelist_gloves', npc:'Кузнец Бран', dust:470, level:4, materials:{ leather:18, iron_ingot:11, essence:2 } },
  mountain_boots: { itemKey:'mountain_boots', npc:'Кузнец Бран', dust:490, level:4, materials:{ leather:18, iron_ingot:13, stone:7 } },
  ring_strength: { itemKey:'ring_strength', npc:'Кузнец Бран', dust:630, level:5, materials:{ iron_ingot:15, crystal:7, essence:2 } },
  sun_amulet: { itemKey:'sun_amulet', npc:'Кузнец Бран', dust:680, level:5, materials:{ crystal:7, essence:7, ancient_fragment:2 } },
  shadow_dagger: { itemKey:'shadow_dagger', npc:'Кузнец Бран', dust:1490, level:7, materials:{ iron_ingot:40, crystal:15, essence:11, void_crystal:2 } },
  paladin_plate: { itemKey:'paladin_plate', npc:'Кузнец Бран', dust:1575, level:7, materials:{ iron_ingot:55, leather:18, crystal:11, ancient_fragment:7 } },
  seer_crown: { itemKey:'seer_crown', npc:'Кузнец Бран', dust:1435, level:7, materials:{ crystal:18, essence:15, ancient_fragment:7 } },
  rune_gauntlets: { itemKey:'rune_gauntlets', npc:'Кузнец Бран', dust:1365, level:7, materials:{ iron_ingot:33, crystal:13, essence:11, ancient_fragment:4 } },
  healing_potion_small: { itemKey:'healing_potion_small', npc:'Алхимик Лира', dust:35, level:1, materials:{ herb_extract:4, essence:1 } },
  healing_potion_large: { itemKey:'healing_potion_large', npc:'Алхимик Лира', dust:110, level:4, materials:{ herb_extract:10, essence:4, crystal:1 } },
  swift_tonic: { itemKey:'swift_tonic', npc:'Алхимик Лира', dust:70, level:2, materials:{ herb_extract:6, board:2, essence:1 } },
  fortune_elixir: { itemKey:'fortune_elixir', npc:'Алхимик Лира', dust:160, level:5, materials:{ herb_extract:8, essence:4, crystal:2, ancient_fragment:1 } },
  rage_scroll: { itemKey:'rage_scroll', npc:'Алхимик Лира', dust:230, level:6, materials:{ essence:5, bone:4, crystal:3 } },
  defense_scroll: { itemKey:'defense_scroll', npc:'Алхимик Лира', dust:230, level:6, materials:{ essence:5, stone:5, crystal:3 } },
  fire_scroll: { itemKey:'fire_scroll', npc:'Алхимик Лира', dust:180, level:5, materials:{ herb_extract:4, essence:5, crystal:2 } },
  ice_scroll: { itemKey:'ice_scroll', npc:'Алхимик Лира', dust:180, level:5, materials:{ herb_extract:5, essence:4, crystal:2 } },
  lightning_scroll: { itemKey:'lightning_scroll', npc:'Алхимик Лира', dust:320, level:8, materials:{ essence:8, crystal:5, ancient_fragment:1 } },
  barrier_scroll: { itemKey:'barrier_scroll', npc:'Алхимик Лира', dust:210, level:6, materials:{ essence:5, stone:5, crystal:3 } },
  blessing_scroll: { itemKey:'blessing_scroll', npc:'Алхимик Лира', dust:340, level:8, materials:{ herb_extract:8, essence:7, crystal:4, moon_blossom:1 } },
  weakening_scroll: { itemKey:'weakening_scroll', npc:'Алхимик Лира', dust:340, level:8, materials:{ essence:8, beast_bone:5, crystal:4 } },
  cleanse_scroll: { itemKey:'cleanse_scroll', npc:'Алхимик Лира', dust:230, level:6, materials:{ herb_extract:8, essence:5, moon_blossom:1 } },
  alchemist_bomb: { itemKey:'alchemist_bomb', npc:'Алхимик Лира', dust:420, level:8, materials:{ essence:8, crystal:6, iron_ore:5, void_crystal:1 } },
  healing_potion_supreme: { itemKey:'healing_potion_supreme', npc:'Алхимик Лира', dust:260, level:7, materials:{ herb_extract:16, essence:8, crystal:3, ancient_fragment:1 } },
  sturdy_draught: { itemKey:'sturdy_draught', npc:'Алхимик Лира', dust:150, level:5, materials:{ herb_extract:10, leather:3, essence:3, crystal:1 } },
  treasure_incense: { itemKey:'treasure_incense', npc:'Алхимик Лира', dust:210, level:6, materials:{ herb_extract:8, board:5, essence:5, ancient_fragment:1 } },
  grand_fortune_elixir: { itemKey:'grand_fortune_elixir', npc:'Алхимик Лира', dust:480, level:9, materials:{ herb_extract:15, essence:10, crystal:6, ancient_fragment:3, void_crystal:1 } },
  war_elixir: { itemKey:'war_elixir', npc:'Алхимик Лира', dust:380, level:8, materials:{ essence:9, bone:8, crystal:5, ancient_fragment:2 } },
  stone_skin_elixir: { itemKey:'stone_skin_elixir', npc:'Алхимик Лира', dust:380, level:8, materials:{ essence:8, stone:10, crystal:5, ancient_fragment:2 } },
  greater_alchemist_bomb: { itemKey:'greater_alchemist_bomb', npc:'Алхимик Лира', dust:900, level:11, materials:{ essence:15, crystal:10, iron_ore:10, ancient_fragment:5, void_crystal:3 } },
});

module.exports = { RECIPES };
