const MATERIALS = Object.freeze({
  wood: { name: 'Древесина', icon: '🪵', rarity: 'common', value: 8, description: 'Базовый материал для оружия и инструментов.' },
  iron_ore: { name: 'Железная руда', icon: '⛓️', rarity: 'common', value: 12, description: 'Руда для кузнечного дела.' },
  stone: { name: 'Камень', icon: '🪨', rarity: 'common', value: 7, description: 'Прочный строительный материал.' },
  herb: { name: 'Лечебная трава', icon: '🌿', rarity: 'common', value: 9, description: 'Основа будущих зелий.' },
  bone: { name: 'Кость', icon: '🦴', rarity: 'common', value: 10, description: 'Материал для талисманов и тёмного ремесла.' },
  leather: { name: 'Кожа', icon: '🟫', rarity: 'common', value: 11, description: 'Используется для лёгкой брони.' },
  crystal: { name: 'Магический кристалл', icon: '💎', rarity: 'rare', value: 45, description: 'Накопитель магической энергии.' },
  essence: { name: 'Эссенция', icon: '✨', rarity: 'rare', value: 55, description: 'Редкая субстанция для чар и алхимии.' },
  ancient_fragment: { name: 'Древний фрагмент', icon: '🏺', rarity: 'rare', value: 70, description: 'Обломок исчезнувшей цивилизации.' },
  void_crystal: { name: 'Кристалл Пустоты', icon: '🌀', rarity: 'epic', value: 180, description: 'Опасный материал, наполненный энергией Разлома.' },
  alpha_fang: { name:'Клык Альфы', icon:'🐺', rarity:'rare', value:70, description:'Клык вожака древней стаи.' },
  alpha_hide: { name:'Шкура Альфы', icon:'🟫', rarity:'rare', value:85, description:'Прочная шкура регионального мини-босса.' },
  alpha_blood: { name:'Кровь Альфы', icon:'🩸', rarity:'epic', value:190, description:'Редкий алхимический компонент.' },
  ancient_alpha_fang: { name:'Древний клык Альфы', icon:'🦷', rarity:'epic', value:420, description:'Легендарная находка из Древнего леса.' },
  troll_stone: { name:'Камень тролля', icon:'🪨', rarity:'rare', value:75, description:'Осколок живой горной породы.' },
  troll_hide: { name:'Шкура тролля', icon:'🟫', rarity:'rare', value:95, description:'Материал для особо прочной брони.' },
  troll_core: { name:'Ядро тролля', icon:'💠', rarity:'epic', value:210, description:'Сгусток силы гор.' },
  ancient_troll_rune: { name:'Древняя руна тролля', icon:'🔶', rarity:'epic', value:450, description:'Редчайшая руна горного стража.' },
  hydra_scale: { name:'Чешуя гидры', icon:'🐍', rarity:'rare', value:82, description:'Устойчива к ядам и влаге.' },
  hydra_venom: { name:'Яд гидры', icon:'🧪', rarity:'rare', value:105, description:'Сильный алхимический реагент.' },
  hydra_heart: { name:'Сердце гидры', icon:'💚', rarity:'epic', value:240, description:'Необычно быстро восстанавливает энергию.' },
  ancient_hydra_eye: { name:'Древний глаз гидры', icon:'👁️', rarity:'epic', value:480, description:'Редчайший трофей затопленных земель.' },
  royal_stinger: { name:'Королевское жало', icon:'🦂', rarity:'rare', value:92, description:'Жало Короля Скорпионов.' },
  scorpion_carapace: { name:'Панцирь скорпиона', icon:'🛡️', rarity:'rare', value:105, description:'Крепкий материал пустыни.' },
  scorpion_venom: { name:'Королевский яд', icon:'☠️', rarity:'epic', value:260, description:'Исключительно редкий яд.' },
  sun_scorpio_gem: { name:'Самоцвет Солнечного Скорпиона', icon:'🔆', rarity:'epic', value:520, description:'Сияющий трофей пепельных дюн.' },
  guardian_bone: { name:'Кость Стража', icon:'🦴', rarity:'rare', value:98, description:'Кость, пропитанная древним проклятием.' },
  tomb_rune: { name:'Руна гробницы', icon:'🏺', rarity:'rare', value:120, description:'Фрагмент защитной печати.' },
  guardian_soul: { name:'Душа Стража', icon:'👻', rarity:'epic', value:285, description:'Пленённая энергия хранителя.' },
  royal_funeral_seal: { name:'Царская погребальная печать', icon:'⚜️', rarity:'epic', value:560, description:'Уникальная реликвия затонувших руин.' },
  frost_fur: { name:'Морозный мех', icon:'🐻‍❄️', rarity:'rare', value:110, description:'Необычайно тёплый мех.' },
  ice_claw: { name:'Ледяной коготь', icon:'❄️', rarity:'rare', value:125, description:'Коготь, не тающий даже у огня.' },
  frozen_heart: { name:'Замёрзшее сердце', icon:'🧊', rarity:'epic', value:310, description:'Сердце ледяного чудовища.' },
  eternal_ice_eye: { name:'Око вечного льда', icon:'🔹', rarity:'epic', value:600, description:'Редчайший трофей ледяных пустошей.' },
  golem_obsidian: { name:'Обсидиан Голема', icon:'⚫', rarity:'rare', value:125, description:'Раскалённый обломок брони голема.' },
  molten_core: { name:'Расплавленное ядро', icon:'🌋', rarity:'rare', value:150, description:'Источник вулканической энергии.' },
  golem_heart: { name:'Сердце Голема', icon:'🔥', rarity:'epic', value:350, description:'Основа будущего легендарного крафта.' },
  titan_ember: { name:'Уголь Титана', icon:'☀️', rarity:'epic', value:700, description:'Почти мифический осколок огненной силы.' },
});

const CHESTS = Object.freeze({
  common_chest: { name: 'Обычный сундук', icon: '📦', rarity: 'common', materialRolls: [2, 3], dust: [25, 60], itemChance: 0.08 },
  rare_chest: { name: 'Редкий сундук', icon: '🎁', rarity: 'rare', materialRolls: [3, 4], dust: [60, 120], itemChance: 0.22 },
  epic_chest: { name: 'Эпический сундук', icon: '🧰', rarity: 'epic', materialRolls: [4, 5], dust: [120, 230], itemChance: 0.42 },
  legendary_chest: { name: 'Легендарный сундук', icon: '👑', rarity: 'legendary', materialRolls: [5, 6], dust: [250, 450], itemChance: 0.70 },
  boss_chest: { name: 'Сундук мирового босса', icon: '🐉', rarity: 'boss', materialRolls: [5, 7], dust: [180, 380], itemChance: 0.62 },
});

const LOCATION_MATERIALS = Object.freeze({
  whispering_forest: ['wood', 'herb', 'leather'],
  misty_marsh: ['herb', 'essence', 'bone'],
  sunken_ruins: ['stone', 'ancient_fragment', 'crystal'],
  iron_mountains: ['iron_ore', 'stone', 'crystal'],
  ash_desert: ['stone', 'leather', 'ancient_fragment'],
  moon_catacombs: ['bone', 'essence', 'crystal'],
  crimson_citadel: ['iron_ore', 'bone', 'ancient_fragment'],
  void_rift: ['essence', 'crystal', 'void_crystal'],
});

module.exports = { MATERIALS, CHESTS, LOCATION_MATERIALS };
