const { createCanvas } = require('canvas');

const DIFF = {
  easy:{label:'ЛЁГКАЯ',accent:'#62e6a7'}
  medium:{label:'СРЕДНЯЯ',accent:'#b879ff'}
  hard:{label:'СЛОЖНАЯ',accent:'#ffbf66'}
};
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function glowText(ctx,text,x,y,size,accent,align='left'){
  ctx.save();ctx.font=`700 ${size}px Arial`;ctx.textAlign=align;ctx.fillStyle='#fff';ctx.shadowColor=accent;ctx.shadowBlur=18;ctx.fillText(text,x,y);ctx.restore();
}
function wrap(ctx,text,maxWidth){const words=text.split(' ');const lines=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);return lines;}
function background(ctx,w,h,accent){const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#090611');g.addColorStop(.55,'#170b2e');g.addColorStop(1,'#07040e');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<70;i++){ctx.globalAlpha=.12+Math.random()*.25;ctx.fillStyle=i%3?accent:'#fff';ctx.beginPath();ctx.arc(Math.random()*w,Math.random()*h,Math.random()*2+1,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
async function createRiddleCard(riddle){const w=1400,h=760,c=createCanvas(w,h),ctx=c.getContext('2d');const d=DIFF[riddle.difficulty]||DIFF.medium;background(ctx,w,h,d.accent);ctx.strokeStyle=d.accent;ctx.lineWidth=3;ctx.shadowColor=d.accent;ctx.shadowBlur=24;rounded(ctx,45,45,w-90,h-90,32);ctx.stroke();ctx.shadowBlur=0;glowText(ctx,'GS RIDDLE',85,120,34,d.accent);ctx.fillStyle=d.accent;ctx.font='700 22px Arial';ctx.fillText(`${d.label} • РАЗ В 3 ЧАСА`,85,165);rounded(ctx,85,215,w-170,300,28);ctx.fillStyle='rgba(20,10,38,.82)';ctx.fill();ctx.strokeStyle='rgba(184,121,255,.45)';ctx.stroke();ctx.font='700 44px Arial';ctx.fillStyle='#fff';const lines=wrap(ctx,riddle.question,w-270);let y=315;for(const line of lines){ctx.fillText(line,135,y);y+=65;}ctx.fillStyle='#bcb0d0';ctx.font='24px Arial';ctx.fillText('Первый правильный ответ побеждает • до 3 уникальных попыток',85,590);ctx.fillStyle=d.accent;ctx.font='700 27px Arial';ctx.fillText('НАГРАДЫ: DUST • XP • РЕДКИЙ ШАНС НА ПАК',85,650);return c.toBuffer('image/png');}
async function createRiddleWinnerCard(data){const w=1400,h=760,c=createCanvas(w,h),ctx=c.getContext('2d');const d=DIFF[data.difficulty]||DIFF.medium;background(ctx,w,h,d.accent);ctx.strokeStyle='#ffd978';ctx.lineWidth=4;ctx.shadowColor='#ffd978';ctx.shadowBlur=28;rounded(ctx,45,45,w-90,h-90,32);ctx.stroke();ctx.shadowBlur=0;glowText(ctx,'ЗАГАДКА РАЗГАДАНА',700,125,42,'#ffd978','center');ctx.fillStyle='#bcb0d0';ctx.font='24px Arial';ctx.textAlign='center';ctx.fillText(data.question,700,205);ctx.textAlign='left';rounded(ctx,150,270,1100,280,28);ctx.fillStyle='rgba(20,10,38,.88)';ctx.fill();ctx.strokeStyle='rgba(255,217,120,.55)';ctx.stroke();glowText(ctx,data.winnerName,700,365,58,d.accent,'center');ctx.fillStyle='#bcb0d0';ctx.font='24px Arial';ctx.textAlign='center';ctx.fillText('ПЕРВЫЙ ПРАВИЛЬНЫЙ ОТВЕТ',700,410);glowText(ctx,data.reward.label,700,500,48,'#ffd978','center');ctx.fillStyle='#bcb0d0';ctx.font='22px Arial';ctx.fillText(data.reward.details||'',700,590);ctx.fillStyle=d.accent;ctx.font='700 22px Arial';ctx.fillText('Следующая загадка — через 3 часа',700,665);return c.toBuffer('image/png');}
module.exports={createRiddleCard,createRiddleWinnerCard};
